#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

source activate isocket
cd web
python -m unittest discover unit_tests/.

if [ $? -eq 1 ]
then
  echo "Unit tests failed while pushing isocket branch, please check them and repush."
  exit 1
else
  echo "isocket unit tests passed, pushing."
fi

exit 0
