"""empty message

Revision ID: c72f4fbb0808
Revises: None
Create Date: 2016-12-16 12:58:23.580917

"""

# revision identifiers, used by Alembic.
revision = 'c72f4fbb0808'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cdhit_full')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cdhit_full',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('c90', sa.BOOLEAN(), nullable=True),
    sa.Column('c80', sa.BOOLEAN(), nullable=True),
    sa.Column('c70', sa.BOOLEAN(), nullable=True),
    sa.Column('c60', sa.BOOLEAN(), nullable=True),
    sa.Column('pdb_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['pdb_id'], ['pdb.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###
